### ISSUE TITLE
[Ad Report] virgool.io

### ISSUE THREAD

**Issue by mimvahedi** [MasterKia/PersianBlocker#215]
سلام، من برای حذف تبلیغات سایت ویرگول(virgool.io) از userStyle زیر استفاده می‌کنم
```css
@-moz-document domain("virgool.io") {
.feedStream-container.feedlistStream > :not(.streamItem, .jscroll-inner, .listItemPlaceholder, .feedStreamLoading),
.streamItem:has(.has-promoted),
[class*=feedAds] {
  display: none !important;
}
}
```
و برای حذف تبلیغات لینک‌ها هم از userScript زیر
```js
// ==UserScript==
// @name        virgool.io  ads remover
// @description   remove ads from virgool.io
// @match       https://virgool.io/*
// @version     1.0
// @author      mimv
// ==/UserScript==

const $ = (x) => document.querySelectorAll(x)

function rmads() {
  document.querySelectorAll('a[href*="l.vrgl.ir"]').forEach(a => a.href = decodeURIComponent(new URL(a).search.slice(1).split("&").find(x => x.split("=")[0] === "l").split("=")[1]))
}

document.addEventListener("scroll", rmads)
```
